import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { Menu } from "lucide-react";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <Head>
        <title>dugsi | Modern School Management System</title>
        <meta
          name="description"
          content="Pioneering the next generation of school management systems."
        />
      </Head>
      <body
      // className="min-h-full flex flex-col "
      >
        {/* Navigation */}
        <nav className="fixed top-0 w-full z-50 bg-[#F7F7F7] backdrop-blur-xl ">
          <div className="flex justify-between items-center px-8 py-4 max-w-7xl mx-auto">
            <Image
              src={"/logo.svg"}
              alt="logo"
              width={200}
              height={0}
              style={{ height: "auto" }}
            />

            <div className="hidden md:flex gap-8 items-center">
              <a
                className="text-[#1A365D] font-bold border-b-2 border-[#1A365D] transition-colors"
                href="/"
              >
                Home
              </a>
              <a
                className="text-slate-600 font-medium hover:text-[#1A365D] transition-colors"
                href="/about"
              >
                About
              </a>
              <a
                className="text-slate-600 font-medium hover:text-[#1A365D] transition-colors"
                href="/contact"
              >
                Contact
              </a>
              <a
                className="text-slate-600 font-medium hover:text-[#1A365D] transition-colors"
                href="#"
              >
                Resources
              </a>
            </div>

            <div className="flex items-center gap-4">
              <button className="hidden md:block text-slate-600 font-medium px-4 py-2 hover:text-[#1A365D] transition-all">
                Login
              </button>
              <button className="bg-[#48BB78] text-white px-6 py-2.5 rounded-xl font-bold hover:opacity-90 active:scale-95 transition-all shadow-lg shadow-[#48BB78]/20">
                Get Started
              </button>
              <button className="md:hidden text-[#1A365D]">
                <Menu size={24} />
              </button>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
